/* SPDX-License-Identifier: MIT */
/*
 * mgmtd_apply_ssl.c — Steering HTTPS traffic into stargazer-ssld (SSL inspection)
 *
 * When an accept policy assigns `security_ssl-inspection-profile` (enabled), we
 * REDIRECT forwarded TLS flows to the ssld listen port with a rule in
 * *nat PREROUTING:
 *
 *   -A PREROUTING -i <srcintf> -p tcp --dport 443 -j REDIRECT --to-ports 8443
 *
 * LOOP PREVENTION — why `-m owner` is NOT needed here:
 *   The connection ssld opens OUT to the real server is traffic generated by the
 *   firewall ITSELF (local-out) → it goes through the OUTPUT chain, NOT back
 *   through PREROUTING. So the REDIRECT rule in PREROUTING never catches ssld's
 *   own traffic → no loop. The correct limiting mechanism is SCOPING BY INTERNAL
 *   INTERFACE (`-i srcintf`): only redirect traffic COMING FROM the LAN side, do
 *   not touch box-generated traffic, do not touch traffic arriving from WAN.
 *   (`-m owner` is only valid in OUTPUT/POSTROUTING; placing it in PREROUTING
 *   would error — so never use it here.)
 *
 * This rule is embedded into the *nat restore of rebuild_nat_chains() so that the
 * whole nat table is restored atomically (no flush conflict with user DNAT/SNAT).
 *
 * Fail-safe: missing config / disabled / dirty input → emit NO rule → traffic
 * flows normally (not blocked). SSL inspection is optional, off-by-default.
 */

#include "mgmtd_apply.h"
#include "mgmtd_dynbuf.h"
#include "mgmtd_internal.h"   /* send_ok/send_error, get_user_permissions */
#include "sg_db.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>         /* open — staged cert/key files */
#include <sys/stat.h>      /* stat — active.rules mtime into ssld sig */
#include <unistd.h>

#define SSL_PROF_TYPE  "security_ssl-inspection-profile"
#define SSL_PORT_BASE  8443    /* ssld profile #i listens on port BASE+i */
#define SSL_SET_FILE   "/run/stargazer-ssld.set"  /* set of running profiles */
#define SSL_DEF_LISTEN "8443"

#define SSLD_BIN       "/sbin/stargazer-ssld"
#define SSLD_CHILD     "stargazer-ssld"
#define SSL_DIR        "/etc/stargazer/ssl"
#define SSL_CACERT     SSL_DIR "/ca-cert.pem"
#define SSL_CAKEY      SSL_DIR "/ca-key.pem"
#define SSL_EXEMPT     SSL_DIR "/exempt.txt"
#define SSL_CFG_SIG    "/run/stargazer-ssld.cfg"
#define SSL_IPS_RULES  "/etc/stargazer/ips/rules/active.rules"

/* IPS profile id carried in the connmark bits 3-7 — MUST match
 * src/userspace/ipsd/nfq.h and mgmtd_apply_firewall.c. On the HTTPS deep-inspect
 * path the flow is REDIRECTed to ssld and never hits the FORWARD MARK rule, so we
 * stamp the profile id into the connmark in the SG_SSLD (filter INPUT) chain; ipsd
 * recovers it from the leg's conntrack entry (CTA_MARK) on the inspection IPC. */
#define SG_CMK_IPS_PROFID_SHIFT 3
#define SG_CMK_IPS_PROFID_MASK  0xF8u

/* Interface name safe for iptables (alnum . _ - @, reasonable length). */
static int valid_ifname(const char *s)
{
	if (!s || !*s || strlen(s) > 31)
		return 0;
	for (const char *p = s; *p; p++) {
		char c = *p;
		if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
		      (c >= '0' && c <= '9') ||
		      c == '.' || c == '_' || c == '-' || c == '@'))
			return 0;
	}
	return 1;
}

static int is_any(const char *s)
{
	return !s || !*s || !strcmp(s, "any") || !strcmp(s, "all");
}

/* Dotted IPv4 safe for iptables-restore (digits + 3 dots only). The value already
 * passed the "ipv4" validator at config time; this is defence-in-depth. */
static int valid_ipv4(const char *s)
{
	if (!s || !*s || strlen(s) > 15)
		return 0;
	int dots = 0;
	for (const char *p = s; *p; p++) {
		if (*p == '.')      dots++;
		else if (*p < '0' || *p > '9')
			return 0;
	}
	return dots == 3;
}

/* ssld port of a profile (enabled, != no-inspection) by DB listing INDEX.
 * Returns >0 if active, 0 if disabled/no-inspection/nonexistent. SHARED by
 * ssld_sync (launch) and emit_ssl_steering (redirect) → consistent ports. */
static int ssl_profile_port(const char *name)
{
	if (!name || !*name || strcmp(name, "no-inspection") == 0)
		return 0;
	char *list = sg_db_list(SSL_PROF_TYPE);
	if (!list)
		return 0;
	int port = 0, idx = 0;
	char *sp = NULL;
	for (char *id = strtok_r(list, "\n", &sp); id;
	     id = strtok_r(NULL, "\n", &sp)) {
		if (strcmp(id, "no-inspection") == 0)
			continue;
		char *st = sg_db_get_val(SSL_PROF_TYPE, id, "status");
		int en = st && strcmp(st, "enable") == 0;
		free(st);
		if (!en)
			continue;
		if (strcmp(id, name) == 0) { port = SSL_PORT_BASE + idx; break; }
		idx++;
	}
	free(list);
	return port;
}

/*
 * ssl_steer_allowed — deep SSL inspection only decrypts when the policy has IPS
 * enabled. Returns 1 if the policy is allowed to steer into ssld; 0 if the
 * profile is DEEP but the policy's IPS is off → skip (traffic flows as a normal
 * accept, NO decryption — matching the requirement that "ssl inspection serves
 * IPS"). Certificate mode never decrypts, so it is always allowed to steer
 * (only peeks SNI/splice).
 */
static int ssl_steer_allowed(const char *prof, const char *ips_status,
			     const char *ips_profile)
{
	/* deep = multiple-clients + inspection-method=deep (protecting-server has no
	 * method field → NULL → not deep → always steers, like certificate). */
	char *method = sg_db_get_val(SSL_PROF_TYPE, prof, "inspection-method");
	int is_deep = method && strcmp(method, "deep") == 0;
	free(method);
	if (is_deep && !ips_policy_on(ips_status, ips_profile))
		return 0;
	return 1;
}

/*
 * emit_ssl_steering — PER-POLICY (FortiGate-style). Each accept policy with an
 * ssl-profile (enabled, != no-inspection) → REDIRECT tcp:443 of the policy's
 * srcintf to that profile's ssld port. A policy using no-inspection → NO steer
 * (traffic flows straight through). Fail-safe: dirty input → skip that policy.
 */
int emit_ssl_steering(struct dynbuf *buf)
{
	char *list = sg_db_list("firewall_policy");
	if (!list)
		return 0;
	int n = 0;
	char *sp = NULL;
	for (char *id = strtok_r(list, "\n", &sp); id;
	     id = strtok_r(NULL, "\n", &sp)) {
		char *data = sg_db_get("firewall_policy", id);
		if (!data)
			continue;
		char action[VALBUFSZ], st[VALBUFSZ], srcintf[VALBUFSZ], prof[VALBUFSZ];
		char ipst[VALBUFSZ], ipp[VALBUFSZ];
		extract_val(data, "action",      action,  sizeof(action));
		extract_val(data, "status",      st,      sizeof(st));
		extract_val(data, "srcintf",     srcintf, sizeof(srcintf));
		extract_val(data, "ssl-profile", prof,    sizeof(prof));
		extract_val(data, "ips-status",  ipst,    sizeof(ipst));
		extract_val(data, "ips-profile", ipp,     sizeof(ipp));
		free(data);

		if (strcmp(action, "accept") != 0 || strcmp(st, "enable") != 0)
			continue;
		if (!prof[0] || strcmp(prof, "no-inspection") == 0)
			continue;
		int port = ssl_profile_port(prof);
		if (port <= 0)
			continue;               /* profile disabled/nonexistent */
		if (!is_any(srcintf) && !valid_ifname(srcintf))
			continue;               /* fail-safe against injection */
		if (!ssl_steer_allowed(prof, ipst, ipp))
			continue;               /* deep but IPS off → no decryption */

		/* protect-server (inbound reverse): scope the REDIRECT to the VIP so it
		 * ONLY catches traffic destined to the protected server. Without this the
		 * rule would grab EVERY :443 on the interface → other services / non-VIP
		 * flows would be answered with a forged cert → cert errors. Scoping by VIP
		 * keeps internal + external access to everything else uninterrupted. */
		char *pmode = sg_db_get_val(SSL_PROF_TYPE, prof, "inspection-mode");
		int is_protect = pmode && strcmp(pmode, "protecting-server") == 0;
		free(pmode);
		char *pvip = is_protect
			   ? sg_db_get_val(SSL_PROF_TYPE, prof, "protect-vip") : NULL;
		int have_vip = pvip && valid_ipv4(pvip);

		dbuf_printf(buf, "-A PREROUTING");
		if (!is_any(srcintf))
			dbuf_printf(buf, " -i %s", srcintf);
		if (have_vip)
			dbuf_printf(buf, " -d %s", pvip);
		dbuf_printf(buf, " -p tcp --dport 443 -j REDIRECT --to-ports %d\n",
			    port);
		mgmt_log("INFO", "SSL steering: policy %s prof=%s -i %s%s%s tcp:443 -> :%d",
			 id, prof, is_any(srcintf) ? "any" : srcintf,
			 have_vip ? " -d " : "", have_vip ? pvip : "", port);
		free(pvip);
		n++;
	}
	free(list);
	return n;
}

/* ── Supervisor: start/stop stargazer-ssld per config ───────────────────── */

/* Write the exempt list (SNI separated by comma/space) to `path`, one SNI per line. */
static int write_exempt_to(const char *path, const char *list)
{
	FILE *f = fopen(path, "w");
	if (!f)
		return -1;
	int n = 0;
	if (list && *list) {
		char *dup = strdup(list);
		if (dup) {
			for (char *t = strtok(dup, " ,\t\n"); t;
			     t = strtok(NULL, " ,\t\n")) {
				fprintf(f, "%s\n", t);
				n++;
			}
			free(dup);
		}
	}
	fclose(f);
	return n;
}

/*
 * Write a one-entry reverse map (revmap.h format) for a protect-server profile:
 *   <vip>:443 <cert> <key> <backend>:<bport> <sni>
 * Returns 0 if all required fields are present (file written), -1 otherwise
 * (caller then skips -R → ssld runs without inbound inspection, fail-safe).
 */
static int write_reverse_to(const char *path, const char *vip, const char *cert,
			    const char *key, const char *backend,
			    const char *bport, const char *sni)
{
	if (!vip || !*vip || !cert || !*cert || !key || !*key ||
	    !backend || !*backend)
		return -1;
	FILE *f = fopen(path, "w");
	if (!f)
		return -1;
	fprintf(f, "%s:443 %s %s %s:%s %s\n", vip, cert, key, backend,
		(bport && *bport) ? bport : "443", (sni && *sni) ? sni : "-");
	fclose(f);
	return 0;
}

/* 1 if any enabled accept policy that uses ssl-profile `prof` also has IPS on
 * (certificate mode passes -I so ssld knows whether to run the IPS ML check). */
static int profile_bound_ips_on(const char *prof)
{
	char *list = sg_db_list("firewall_policy");
	if (!list)
		return 0;
	int on = 0;
	char *sp = NULL;
	for (char *id = strtok_r(list, "\n", &sp); id && !on;
	     id = strtok_r(NULL, "\n", &sp)) {
		char *data = sg_db_get("firewall_policy", id);
		if (!data)
			continue;
		char action[VALBUFSZ], st[VALBUFSZ], pr[VALBUFSZ];
		char ipst[VALBUFSZ], ipp[VALBUFSZ];
		extract_val(data, "action",      action, sizeof(action));
		extract_val(data, "status",      st,     sizeof(st));
		extract_val(data, "ssl-profile", pr,     sizeof(pr));
		extract_val(data, "ips-status",  ipst,   sizeof(ipst));
		extract_val(data, "ips-profile", ipp,    sizeof(ipp));
		free(data);
		if (strcmp(action, "accept") == 0 && strcmp(st, "enable") == 0 &&
		    strcmp(pr, prof) == 0 && ips_policy_on(ipst, ipp))
			on = 1;
	}
	free(list);
	return on;
}

/* Find the line "name\t<sig>" in the set (prev/desired). cmp_sig!=NULL → return
 * 1 if sig matches; cmp_sig==NULL → return 1 if the name merely exists. */
static int set_has(const char *set, const char *name, const char *cmp_sig)
{
	size_t nl = strlen(name);
	for (const char *p = set; p && *p; ) {
		const char *eol = strchr(p, '\n');
		size_t ll = eol ? (size_t)(eol - p) : strlen(p);
		if (ll > nl && strncmp(p, name, nl) == 0 && p[nl] == '\t') {
			if (!cmp_sig)
				return 1;
			const char *ps = p + nl + 1;
			size_t sl = ll - nl - 1;
			return strlen(cmp_sig) == sl && strncmp(ps, cmp_sig, sl) == 0;
		}
		if (!eol) break;
		p = eol + 1;
	}
	return 0;
}

/*
 * ssld_input_access_sync — open INPUT for TLS packets already REDIRECTed to ssld.
 *
 * After REDIRECT (nat PREROUTING) the packet's destination changes to
 * firewall:<ssld_port> → it becomes local-destined → it goes through the INPUT
 * chain. But INPUT has a DROP policy and each interface has a chain SG_IN_<if>
 * ending in `-j DROP`, which does NOT open the ssld port → NEW packets to the
 * ssld port are dropped, the client never receives SYN-ACK (curl hangs).
 *
 * We open EXACTLY the redirected traffic: by (-i srcintf, --dport ssld_port) of
 * each accept policy currently steering, in a dedicated chain SG_SSLD jumped from
 * the HEAD of INPUT (before the per-interface chains that end in DROP). It is
 * rebuilt wholesale on every sync (flush + repopulate) so rules do not
 * accumulate. No policy steering → empty chain → no-op (packet RETURNs to INPUT
 * and continues normally). Called from ssld_sync, right after the steering
 * REDIRECT has been applied.
 */
static void ssld_input_access_sync(void)
{
	/* Dedicated chain + jump at the head of INPUT (idempotent: -D then -I → exactly 1 jump). */
	const char *mk[] = {"iptables", "-N", "SG_SSLD", NULL};
	free(safe_exec(mk));                    /* ignore error if chain already exists */
	const char *dj[] = {"iptables", "-D", "INPUT", "-j", "SG_SSLD", NULL};
	free(safe_exec(dj));                    /* ignore error if jump does not exist yet */
	const char *ij[] = {"iptables", "-I", "INPUT", "-j", "SG_SSLD", NULL};
	ipt_exec(ij);
	const char *fl[] = {"iptables", "-F", "SG_SSLD", NULL};
	ipt_exec(fl);

	char *list = sg_db_list("firewall_policy");
	if (!list)
		return;
	char *sp = NULL;
	for (char *id = strtok_r(list, "\n", &sp); id;
	     id = strtok_r(NULL, "\n", &sp)) {
		char *data = sg_db_get("firewall_policy", id);
		if (!data)
			continue;
		char action[VALBUFSZ], st[VALBUFSZ], srcintf[VALBUFSZ], prof[VALBUFSZ];
		char ipst[VALBUFSZ], ipp[VALBUFSZ];
		extract_val(data, "action",      action,  sizeof(action));
		extract_val(data, "status",      st,      sizeof(st));
		extract_val(data, "srcintf",     srcintf, sizeof(srcintf));
		extract_val(data, "ssl-profile", prof,    sizeof(prof));
		extract_val(data, "ips-status",  ipst,    sizeof(ipst));
		extract_val(data, "ips-profile", ipp,     sizeof(ipp));
		free(data);

		if (strcmp(action, "accept") != 0 || strcmp(st, "enable") != 0)
			continue;
		if (!prof[0] || strcmp(prof, "no-inspection") == 0)
			continue;
		int port = ssl_profile_port(prof);
		if (port <= 0)
			continue;               /* profile disabled/nonexistent */
		if (!is_any(srcintf) && !valid_ifname(srcintf))
			continue;               /* fail-safe against injection */
		if (!ssl_steer_allowed(prof, ipst, ipp))
			continue;               /* deep but IPS off → no decryption */

		char portstr[16];
		snprintf(portstr, sizeof(portstr), "%d", port);

		/* Per-policy IPS scoping for the bumped flow: stamp the profile id
		 * into the connmark (bits 3-7) so ipsd can recover it from conntrack
		 * (this flow never traverses the FORWARD MARK rule). CONNMARK is
		 * non-terminating → placed BEFORE the ACCEPT in the same chain, same
		 * match. Only when the flow will actually be inspected (IPS on). */
		char xmark[24] = "";
		if (ips_policy_on(ipst, ipp)) {
			int pid = ips_profid(ipp);
			if (pid >= 1 && pid <= 31)
				snprintf(xmark, sizeof(xmark), "0x%x/0x%x",
					 (unsigned)pid << SG_CMK_IPS_PROFID_SHIFT,
					 SG_CMK_IPS_PROFID_MASK);
		}
		if (is_any(srcintf)) {
			if (xmark[0]) {
				const char *cm[] = {"iptables", "-A", "SG_SSLD",
					"-p", "tcp", "-m", "tcp", "--dport", portstr,
					"-j", "CONNMARK", "--set-xmark", xmark, NULL};
				ipt_exec(cm);
			}
			const char *a[] = {"iptables", "-A", "SG_SSLD",
				"-p", "tcp", "-m", "tcp", "--dport", portstr,
				"-j", "ACCEPT", NULL};
			ipt_exec(a);
		} else {
			if (xmark[0]) {
				const char *cm[] = {"iptables", "-A", "SG_SSLD",
					"-i", srcintf, "-p", "tcp", "-m", "tcp",
					"--dport", portstr,
					"-j", "CONNMARK", "--set-xmark", xmark, NULL};
				ipt_exec(cm);
			}
			const char *a[] = {"iptables", "-A", "SG_SSLD",
				"-i", srcintf, "-p", "tcp", "-m", "tcp",
				"--dport", portstr, "-j", "ACCEPT", NULL};
			ipt_exec(a);
		}
		mgmt_log("INFO", "SSL input-access: policy %s -i %s tcp/%d ACCEPT%s",
			 id, is_any(srcintf) ? "any" : srcintf, port,
			 xmark[0] ? " (+profid connmark)" : "");
	}
	free(list);
}

/*
 * ssld_sync — reconcile ONE ssld per profile (option-1). Each enabled profile
 * (!= no-inspection) → 1 ssld listening on port BASE+idx with the profile's
 * settings. A profile that is deleted/disabled/reconfigured → stop/restart the
 * right instance. Called AFTER rebuild_nat_chains. Child name =
 * "stargazer-ssld-<profile>".
 */
void ssld_sync(void)
{
	/* Migration: stop the old model's single ssld if it is still running. */
	if (supervisor_get_pid(SSLD_CHILD) > 0)
		supervisor_stop(SSLD_CHILD);

	char prev[4096] = "";
	FILE *pf = fopen(SSL_SET_FILE, "r");
	if (pf) { size_t r = fread(prev, 1, sizeof(prev) - 1, pf); prev[r] = '\0'; fclose(pf); }

	char desired[4096]; size_t dpos = 0; desired[0] = '\0';
	int have_bin = access(SSLD_BIN, X_OK) == 0;

	/* active.rules mtime → into each profile's sig: rules change → sig changes →
	 * ssld restarts to load the new ruleset (ssld loads rules at startup, no
	 * hot-reload like ipsd). rebuild_ips_active calls ssld_sync() after swapping
	 * active.rules. */
	struct stat rst;
	long rules_mtime = (stat(SSL_IPS_RULES, &rst) == 0) ? (long)rst.st_mtime : 0;

	/* Phase 4: global IPC flags (security_ips). ipc-inspect=disable → ssld
	 * inspects per-chunk (-Q). ipc-failmode=closed → ssld blocks the flow when
	 * IPC fails (-F). */
	char *ipc_insp = sg_db_get_val("security_ips", "0", "ipc-inspect");
	char *ipc_fm   = sg_db_get_val("security_ips", "0", "ipc-failmode");
	int ipc_off    = ipc_insp && strcmp(ipc_insp, "disable") == 0;
	int ipc_closed = ipc_fm   && strcmp(ipc_fm, "closed") == 0;
	free(ipc_insp); free(ipc_fm);

	char *list = sg_db_list(SSL_PROF_TYPE);
	int idx = 0;
	if (list) {
		char *sp = NULL;
		for (char *id = strtok_r(list, "\n", &sp); id;
		     id = strtok_r(NULL, "\n", &sp)) {
			if (strcmp(id, "no-inspection") == 0)
				continue;
			char *stt = sg_db_get_val(SSL_PROF_TYPE, id, "status");
			int en = stt && strcmp(stt, "enable") == 0;
			free(stt);
			if (!en)
				continue;
			int port = SSL_PORT_BASE + idx; idx++;

			char *mode   = sg_db_get_val(SSL_PROF_TYPE, id, "inspection-mode");
			char *method = sg_db_get_val(SSL_PROF_TYPE, id, "inspection-method");
			char *nosni  = sg_db_get_val(SSL_PROF_TYPE, id, "no-sni");
			char *untr   = sg_db_get_val(SSL_PROF_TYPE, id, "untrusted-server-cert");
			char *exempt = sg_db_get_val(SSL_PROF_TYPE, id, "exempt");
			/* mode = direction; method (multiple-clients only) = certificate|deep */
			int protect      = mode && strcmp(mode, "protecting-server") == 0;
			int certificate  = !protect && method &&
					   strcmp(method, "certificate") == 0;
			int nosni_splice = nosni && strcmp(nosni, "splice") == 0;
			int untr_block   = !untr || strcmp(untr, "block") == 0;

			/* protect-server (inbound reverse): write this profile's reverse map.
			 * server-cert is the NAME of an imported certificate; resolve it to
			 * the PEM files written by the import path. */
			char *sc=NULL,*pvip=NULL,*pbk=NULL,*pbp=NULL,*psni=NULL;
			char certpath[300]="", keypath[300]="";
			char revfile[256]; int rev_ok = 0; long cert_mtime = 0;
			snprintf(revfile, sizeof(revfile), "%s/reverse-%s.rev", SSL_DIR, id);
			if (protect) {
				sc   = sg_db_get_val(SSL_PROF_TYPE, id, "server-cert");
				pvip = sg_db_get_val(SSL_PROF_TYPE, id, "protect-vip");
				pbk  = sg_db_get_val(SSL_PROF_TYPE, id, "protect-backend");
				pbp  = sg_db_get_val(SSL_PROF_TYPE, id, "protect-backend-port");
				psni = sg_db_get_val(SSL_PROF_TYPE, id, "protect-sni");
				if (sc && *sc) {
					snprintf(certpath, sizeof(certpath),
						 "%s/certs/%s/cert.pem", SSL_DIR, sc);
					snprintf(keypath, sizeof(keypath),
						 "%s/certs/%s/key.pem", SSL_DIR, sc);
				}
				rev_ok = (write_reverse_to(revfile, pvip,
						certpath[0] ? certpath : NULL,
						keypath[0]  ? keypath  : NULL,
						pbk, pbp, psni) == 0);
				if (!rev_ok)
					mgmt_log("WARN", "ssld_sync: profile %s protect-server "
						 "missing cert/vip/backend — inbound "
						 "inspection disabled", id);
				else {
					struct stat cst;   /* cert rotated in place → restart */
					if (certpath[0] && stat(certpath, &cst) == 0)
						cert_mtime = (long)cst.st_mtime;
				}
			}

			char exfile[256], portstr[16], child[128], sig[2048];
			snprintf(exfile, sizeof(exfile),
				 "/etc/stargazer/ssl/exempt-%s.txt", id);
			write_exempt_to(exfile, exempt);

			/* certificate mode: web-filter block list + whether IPS is on */
			char *blocksni = certificate
				? sg_db_get_val(SSL_PROF_TYPE, id, "block-sni") : NULL;
			char blockfile[256]; int block_n = 0;
			snprintf(blockfile, sizeof(blockfile), "%s/block-%s.txt", SSL_DIR, id);
			if (certificate)
				block_n = write_exempt_to(blockfile, blocksni);
			int prof_ips_on = certificate ? profile_bound_ips_on(id) : 0;

			snprintf(portstr, sizeof(portstr), "%d", port);
			snprintf(child, sizeof(child), "stargazer-ssld-%s", id);
			snprintf(sig, sizeof(sig),
				 "%d|%d|%d|%d|%d|%d|%ld|%s|P%d|%ld|%s|%s|%s|%s|%s|%s|C%d|%s",
				 port, certificate, nosni_splice, untr_block, ipc_off,
				 ipc_closed, rules_mtime, exempt ? exempt : "",
				 protect, cert_mtime, sc?sc:"", keypath, pvip?pvip:"",
				 pbk?pbk:"", pbp?pbp:"", psni?psni:"",
				 prof_ips_on, blocksni ? blocksni : "");
			dpos += (size_t)snprintf(desired + dpos, sizeof(desired) - dpos,
						 "%s\t%s\n", id, sig);

			int running = supervisor_get_pid(child) > 0;
			if (running && set_has(prev, id, sig)) {
				/* already running with the right config → leave as is */
			} else if (have_bin) {
				if (running) supervisor_stop(child);
				const char *argv[24]; int ai = 0;
				argv[ai++] = SSLD_BIN;
				argv[ai++] = "-p"; argv[ai++] = portstr;
				if (certificate) {
					argv[ai++] = "-C";   /* certificate inspection */
					if (block_n > 0) { argv[ai++] = "-L"; argv[ai++] = blockfile; }
					if (prof_ips_on)   argv[ai++] = "-I";
				}
				if (nosni_splice) argv[ai++] = "-B";
				if (untr_block)   argv[ai++] = "-V";
				if (ipc_off)      argv[ai++] = "-Q";   /* P4: disable IPC */
				if (ipc_closed)   argv[ai++] = "-F";   /* P4: fail-closed */
				if (exempt && *exempt) { argv[ai++] = "-b"; argv[ai++] = exfile; }
				/* Only hand ssld the rule table in per-chunk mode
				 * (ipc-inspect=disable): then it builds its own
				 * automaton. In the default IPC mode it forwards
				 * decrypted plaintext to ipsd, so it needs NO rules
				 * (saves a second ~automaton). */
				if (ipc_off && access(SSL_IPS_RULES, R_OK) == 0) {
					argv[ai++] = "-r"; argv[ai++] = SSL_IPS_RULES;
				}
				if (protect) {
					/* protect-server: NEVER forward-forge. Matched VIP →
					 * reverse (real cert). Anything else (non-VIP that slipped
					 * through, or a misconfigured/missing cert) → splice, so the
					 * server stays reachable instead of answering with a forged
					 * cert. -S disables forge but leaves reverse (revmap) intact. */
					argv[ai++] = "-S";
					if (rev_ok) { argv[ai++] = "-R"; argv[ai++] = revfile; }
				}
				argv[ai++] = "-c"; argv[ai++] = SSL_CACERT;
				argv[ai++] = "-k"; argv[ai++] = SSL_CAKEY;
				argv[ai] = NULL;
				if (supervisor_start(child, argv, SRC_CONFIG,
						     SSL_PROF_TYPE, id, "status", "enable") != 0)
					mgmt_log("ERROR", "ssld_sync: start %s failed", child);
				else
					mgmt_log("INFO", "ssld_sync: %s running :%d mode=%s",
						 child, port,
						 protect ? "protecting-server"
						 : certificate ? "certificate" : "deep");
			} else {
				mgmt_log("WARN", "ssld_sync: %s missing — profile %s "
					 "cannot be inspected (that HTTPS policy may break)",
					 SSLD_BIN, id);
			}
			free(mode); free(method); free(nosni); free(untr); free(exempt);
			free(sc); free(pvip); free(pbk); free(pbp); free(psni);
			free(blocksni);
		}
		free(list);
	}

	/* Stop instances in prev no longer in desired (profile removed/disabled). */
	for (const char *p = prev; *p; ) {
		const char *eol = strchr(p, '\n');
		size_t ll = eol ? (size_t)(eol - p) : strlen(p);
		const char *tab = memchr(p, '\t', ll);
		if (tab) {
			char name[96];
			size_t nl = (size_t)(tab - p);
			if (nl < sizeof(name)) {
				memcpy(name, p, nl); name[nl] = '\0';
				if (!set_has(desired, name, NULL)) {
					char child[128];
					snprintf(child, sizeof(child),
						 "stargazer-ssld-%s", name);
					if (supervisor_get_pid(child) > 0) {
						supervisor_stop(child);
						mgmt_log("INFO", "ssld_sync: stopped %s "
							 "(profile removed/disabled)", child);
					}
				}
			}
		}
		if (!eol) break;
		p = eol + 1;
	}

	FILE *wf = fopen(SSL_SET_FILE, "w");
	if (wf) { fwrite(desired, 1, dpos, wf); fclose(wf); }

	/* Open INPUT for packets already REDIRECTed to ssld (otherwise INPUT DROP
	 * swallows them all → client hangs). Run AFTER knowing which profiles/ports
	 * are active. */
	ssld_input_access_sync();
}

/* ── Certificate import (SG_CMD_CERT_IMPORT) ─────────────────────────────────
 *
 * Imported certificates are stored as PEM files under
 * /etc/stargazer/ssl/certs/<name>/{cert.pem,key.pem}; the DB carries only
 * metadata (system_certificate) so they appear in the cert dropdown. mgmtd does
 * NOT link OpenSSL, so it only checks the PEM markers — it does not parse X.509.
 * A protect-server ssl-profile resolves server-cert=<name> to these files in
 * ssld_sync(). The PEM material itself is staged to disk by webd/CLI; the IPC
 * payload carries only the staged paths + name (well under SG_PAYLOAD_MAX).
 */
#define CERT_DIR  SSL_DIR "/certs"
#define CERT_MAX  65536

/* Copy the value of a `key=...` line out of a text payload. 1 if found. */
static int cert_payload_get(const char *payload, const char *key,
			    char *out, size_t outsz)
{
	out[0] = '\0';
	if (!payload) return 0;
	size_t klen = strlen(key);
	for (const char *p = payload; *p; ) {
		const char *eol = strchr(p, '\n');
		size_t ll = eol ? (size_t)(eol - p) : strlen(p);
		if (ll > klen && strncmp(p, key, klen) == 0 && p[klen] == '=') {
			size_t vlen = ll - klen - 1;
			if (vlen >= outsz) vlen = outsz - 1;
			memcpy(out, p + klen + 1, vlen);
			out[vlen] = '\0';
			return 1;
		}
		if (!eol) break;
		p = eol + 1;
	}
	return 0;
}

static ssize_t cert_read_file(const char *path, char *buf, size_t bufsz)
{
	int fd = open(path, O_RDONLY);
	if (fd < 0) return -1;
	ssize_t n = read(fd, buf, bufsz - 1);
	close(fd);
	if (n < 0) return -1;
	buf[n] = '\0';
	return n;
}

static int cert_write_file(const char *path, const char *buf, size_t len,
			   mode_t mode)
{
	int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, mode);
	if (fd < 0) return -1;
	ssize_t w = write(fd, buf, len);
	close(fd);
	return (w == (ssize_t)len) ? 0 : -1;
}

int handle_cert_import(int client_fd, const char *user,
		       const char *payload, const sg_request_hdr_t *hdr)
{
	(void)hdr;
	const char *perms = get_user_permissions(user);
	if (!has_permission(perms, "admin")) {
		send_error(client_fd, SG_ERR_PERM_DENIED,
			   "admin permission required");
		return 0;
	}

	char name[128], certp[256], keyp[256], comment[256];
	cert_payload_get(payload, "name", name, sizeof(name));
	cert_payload_get(payload, "cert", certp, sizeof(certp));
	cert_payload_get(payload, "key",  keyp,  sizeof(keyp));
	cert_payload_get(payload, "comment", comment, sizeof(comment));

	if (!sg_is_safe_id(name)) {
		send_error(client_fd, SG_ERR_INVALID_ARG,
			   "invalid certificate name (letters/digits/-_. only)");
		return 0;
	}
	if (!certp[0]) {
		send_error(client_fd, SG_ERR_INVALID_ARG, "no certificate file");
		return 0;
	}

	/* Read + sanity-check the staged PEM(s). */
	char cbuf[CERT_MAX];
	ssize_t cn = cert_read_file(certp, cbuf, sizeof(cbuf));
	if (cn <= 0 || !strstr(cbuf, "-----BEGIN CERTIFICATE-----")) {
		send_error(client_fd, SG_ERR_INVALID_VAL,
			   "certificate file is not a PEM certificate");
		return 0;
	}
	int have_key = 0;
	char kbuf[CERT_MAX];
	ssize_t kn = 0;
	if (keyp[0]) {
		kn = cert_read_file(keyp, kbuf, sizeof(kbuf));
		if (kn <= 0 || !strstr(kbuf, "PRIVATE KEY-----")) {
			send_error(client_fd, SG_ERR_INVALID_VAL,
				   "key file is not a PEM private key");
			return 0;
		}
		have_key = 1;
	}

	/* Write into /etc/stargazer/ssl/certs/<name>/ */
	char dir[256], cdst[320], kdst[320];
	mkdir(SSL_DIR, 0700);
	mkdir(CERT_DIR, 0700);
	snprintf(dir, sizeof(dir), "%s/%s", CERT_DIR, name);
	mkdir(dir, 0700);
	snprintf(cdst, sizeof(cdst), "%s/cert.pem", dir);
	snprintf(kdst, sizeof(kdst), "%s/key.pem", dir);

	if (cert_write_file(cdst, cbuf, (size_t)cn, 0644) != 0) {
		send_error(client_fd, SG_ERR_INTERNAL, "could not store certificate");
		return 0;
	}
	if (have_key && cert_write_file(kdst, kbuf, (size_t)kn, 0600) != 0) {
		send_error(client_fd, SG_ERR_INTERNAL, "could not store private key");
		return 0;
	}
	/* NOTE: source files are NOT removed here — webd's staged /tmp uploads are
	 * cleaned by flow_cert_import (success + failure), while the CLI passes the
	 * user's own on-device paths which must be left intact. */

	/* DB metadata row → lists in the certificate dropdown. */
	char meta[768];
	snprintf(meta, sizeof(meta), "name=%s\nhas-key=%s\n%s%s%s",
		 name, have_key ? "yes" : "no",
		 comment[0] ? "comment=" : "",
		 comment[0] ? comment : "",
		 comment[0] ? "\n" : "");
	if (sg_db_set("system_certificate", name, meta) != 0) {
		send_error(client_fd, SG_ERR_INTERNAL,
			   "certificate stored but DB update failed");
		return 0;
	}

	/* A protect-server profile may already reference this name (or the cert was
	 * rotated in place) — re-sync so ssld picks up the new material. */
	ssld_sync();

	mgmt_log("INFO", "cert import: '%s' (key=%s)", name,
		 have_key ? "yes" : "no");
	send_ok(client_fd, NULL, "certificate imported");
	return 0;
}
