### DOMAIN:system ###
[system_settings]
hostname=stargazer
ip-forward=enable

[system_admin-profile:read-write]
permissions=monitor,configure,admin
description=Full administrative access
builtin=yes

[system_admin-profile:read-only]
permissions=monitor
description=Read-only monitoring access
builtin=yes

[system_password-policy]
min-length=8
min-uppercase=1
min-lowercase=1
min-digit=1
min-special=0

[system_admin:admin]
profile=read-write
enforce-change-password=enable
enforce-password-policy=enable
builtin=yes

### DOMAIN:firewall ###
[firewall_policy:1]
name=default-deny
srcintf=any
dstintf=any
srcaddr=all
dstaddr=all
action=deny
status=enable
comment=Default deny all traffic
